language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer update {$COMPOSER_FLAGS} --prefer-dist

script: 
  - phpunit
  - php bin/phpbench run --config=examples/phpbench --dump-file=dump.xml
  - cat dump.xml

env:
    - COMPOSER_FLAGS=""
    - COMPOSER_FLAGS="--prefer-lowest"
