language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer update ${COMPOSER_FLAGS} --prefer-dist

script: 
  - phpunit
  - php bin/phpbench run --config=examples/phpbench.json --dump-file=dump.xml --report=all --output=console --output=html_example --output=markdown

matrix:
    include:
        - php: 5.4
          env: COMPOSER_FLAGS="--prefer-lowest"
