language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [ -n "${SYMFONY_VERSION}" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi;
  - composer update ${COMPOSER_FLAGS} --prefer-dist
  # avoid timezone warnings
  - export TZ=Europe/Paris

script: 
  - phpunit
  # run the benchmarks in order to test them
  - php bin/phpbench run --iterations=1 --revs=1
  - php bin/phpbench run --iterations=1 --revs=1 --config=extensions/sqlite/benchmarks/phpbench.json

matrix:
    include:
        - php: 5.5
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.0
          env: SYMFONY_VERSION=^3.0
