language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 5.7

before_script:
  - composer install
  - echo 'date.timezone = "Europe/Vienna"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit
